### ISSUE TITLE
Cannot push to remote permission denied

### ISSUE THREAD

**Issue by karneaud** [AustP/git-go#7]
I'm trying to use your console to push to a remote server(ssh) but keep getting permission denied( public key denied). 

This does not happen when I use the PC's terminal. 

what could cause this and what would be a possible solution?

**Comment by AustP** [comment]
My guess is that the environment is messed up somehow. Git-go uses the same environment that Atom is using when running commands.

1. Are you running Atom and the native terminal as the same user?
2. What OS are you using?

**Comment by karneaud** [comment]
@AustP 

Aahh....my bad there. I'm on Windows 8.1 and run atom from program file rather than from CLI( forgot that i can launch atom from terminal). Will try this out.
